### ISSUE TITLE
(Error: connect ECONNREFUSED)

### ISSUE THREAD

**Issue by rabeetio** [qrpike/spotify-playlist-downloader#21]
Anybody else getting this error and know a workaround? I see that there was the same issue in the closed issues but there wasnt' really a solution?

Thanks!

**Comment by greensouth** [comment]
Same here, please somebody help?

**Comment by karroffel** [comment]
The problem is within `spotify-web` which is used by this app.
 Seems like the given IP is not valid anymore through changes in the spotify web api. Maybe you need to use a premium account (I only got a free one)

**Comment by karroffel** [comment]
The problem is, that the ping pong server http://ping-pong.spotify.nodestuff.net/ is down. I actually got my own ping pong server up for running, but i cannot download songs because "Track is not playable in country DE" Grrrr
If you want to set up your own ping pong server take a look at
https://github.com/1994rstefan/Spotify-Ping-Pong-API

All you need to do is to change the line 478 in lib/spotify.js in the spotify-web module

**Comment by greensouth** [comment]
Already did, and got
- Processing 100 Tracks
  /usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                          throw(e);
                          ^

Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)

**Comment by karroffel** [comment]
I had to rebuild the protobufjs modules.
Then in `lib/schemas.js` of spotify-web you need to change the line 15
`var protobufjs = require('protobufjs');` to
`var protobufjs = require('/usr/lib/node_modules/protobufjs');`

This worked for me (except that i am unable to download tracks because of the region error)

**Comment by karroffel** [comment]
https://github.com/TooTallNate/node-spotify-web/issues/102#issuecomment-146658814

Got it working (even in Germany ^^)
